# Generated by Django 3.2.9 on 2021-12-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_status',
            field=models.CharField(choices=[('CR', 'Current'), ('CP', 'Completed'), ('PT', 'Potential'), ('CN', 'Canceled'), ('FT', 'Future')], default='PT', max_length=2),
        ),
    ]
