# Generated by Django 3.2.9 on 2021-12-07 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0002_contract_contract_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_checkNumber', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_checkAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('payment_memo', models.CharField(max_length=500)),
            ],
        ),
    ]
