# Generated by Django 3.2.9 on 2021-12-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vcm_app.contract'),
        ),
    ]
