# Generated by Django 3.2.9 on 2021-12-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0007_alter_vendor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeofWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['work'],
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['contract_title']},
        ),
    ]
