# Generated by Django 3.2.9 on 2021-12-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0008_auto_20211208_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofwork',
            name='vendors',
            field=models.ManyToManyField(to='vcm_app.Vendor'),
        ),
    ]
