# Generated by Django 3.2.9 on 2021-12-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0009_typeofwork_vendors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeofWork',
            new_name='WorkType',
        ),
    ]
