# Generated by Django 3.2.9 on 2021-12-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0010_rename_typeofwork_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='vendors',
            field=models.ManyToManyField(blank=True, null=True, to='vcm_app.Vendor'),
        ),
    ]
