# Generated by Django 3.2.9 on 2021-12-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0012_alter_worktype_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='contracts',
            field=models.ManyToManyField(blank=True, to='vcm_app.Contract'),
        ),
    ]
