# Generated by Django 3.2.9 on 2021-12-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0013_worktype_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_pdf',
            field=models.FileField(blank=True, upload_to='contract_pdfs/'),
        ),
    ]
