# Generated by Django 3.2.9 on 2021-12-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0013_worktype_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadName', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='test/')),
            ],
        ),
    ]
