# Generated by Django 3.2.9 on 2021-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0014_contract_contract_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contract_status',
            field=models.CharField(choices=[('B', 'Bidding'), ('R', 'Referral'), ('A', 'Advertisement')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_poc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_website',
            field=models.URLField(blank=True),
        ),
    ]
