# Generated by Django 3.2.9 on 2021-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcm_app', '0014_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='C:\\TEST'),
        ),
    ]
